import {choiceGroup,buttonGroup,numberStepper,dataTable,avatarGroup,breadcrumb,documentTabs,dialog,codeBlock} from './patterns.js';
const p=(type,key,x,y,props={})=>({type,key,x,y,...props});
const b=(type,key,x,y,text,props={})=>p(type,key,x,y,{text,width:146,height:32,action:key,...props});
const note=(key,text,x,y,width=304)=>p('Paragraph',key,x,y,{text,width,height:24,fontSize:12,horizontalPadding:0,color:{expr:'state.theme.textMuted'}});
export const extraSections=[
  {id:'reveal',title:'Reveal',detail:'Подведите курсор к рамке снаружи, затем внутрь.',height:184,parts:'Surface → Reveal\n  pointer position → radial border\n  120 → 1200 px · 280 ms',kind:'RUST · CPU / GPU'},
  {id:'choices',title:'Checkbox и Switch',detail:'Выбор хранится в отдельных Rust-моделях.',height:184,parts:'Checkbox → ChoiceContent\n  ├ ChoiceIndicator → CheckMark\n  └ Label\nSwitch → SwitchThumb',kind:'ВЗАИМОДЕЙСТВИЕ'},
  {id:'radiochips',title:'Radio и Chip',detail:'Один вариант в группе и независимые метки.',height:184,parts:'RadioButton : Checkbox\nSelectionValue · один выбор\nChip + ToggleValue · несколько',kind:'ВЗАИМОДЕЙСТВИЕ'},
  {id:'segments',title:'Группы и вкладки',detail:'Сегменты и вкладки собираются из отдельных кнопок.',height:184,parts:'buttonGroup → SegmentButton[]\nbuttonGroup → TabButton[]\nSelectionValue',kind:'ВЗАИМОДЕЙСТВИЕ'},
  {id:'fields',title:'Текстовые поля',detail:'Набор, выделение, копирование и вставка.',height:244,parts:'TextField → FieldContent\n  ├ Icon\n  └ FieldValue\nSearchField : TextField\nTextInput → Rust TextEdit',kind:'ВЗАИМОДЕЙСТВИЕ'},
  {id:'range',title:'Slider и Stepper',detail:'Общая числовая модель: drag, стрелки и шаг.',height:184,parts:'RangeValue\nSlider → SliderTrack + thumb\nnumberStepper → IconButton\n  + NumberValue + IconButton',kind:'ВЗАИМОДЕЙСТВИЕ'},
  {id:'navigation',title:'Навигация',detail:'Хлебные крошки, пункты меню и страницы.',height:244,parts:'breadcrumb → GhostButton[]\nNavigationItem + active mark\nPageButton[] + prev / next',kind:'ВЗАИМОДЕЙСТВИЕ'},
  {id:'data',title:'Таблица и загрузка',detail:'Строки, ячейки и placeholders — отдельные части.',height:244,parts:'dataTable → TableHeader\n  + TableRow[] → TableCells\nSkeleton · LoadingButton',kind:'КОМПОЗИЦИЯ'},
  {id:'overlays',title:'Select и раскрытие',detail:'Варианты списка и раскрываемая область.',height:244,parts:'SelectTrigger + MenuItem[]\nDisclosureHeader + Paragraph\nОткрытие управляется примером',kind:'ВЗАИМОДЕЙСТВИЕ'},
  {id:'feedback',title:'Dialog, Toast, Tooltip',detail:'Отдельные поверхности, текст и кнопки действий.',height:244,parts:'dialog → DialogSurface\n  + Paragraph + Button[]\nToast : Alert · Tooltip : Surface',kind:'ПРИМЕР В ОБЛАСТИ'},
  {id:'documents',title:'Вкладки документов',detail:'Закрытие, выбор следующей и отдельный dirty-dot.',height:184,parts:'documentTabs → TabButton[]\n  + StatusDot + IconButton\nМесто для крестика зарезервировано',kind:'ВЗАИМОДЕЙСТВИЕ'},
  {id:'tree',title:'Дерево',detail:'Раскрытие папок и навигация стрелками.',height:244,parts:'TreeValue → visible rows\nTreeItem → TreeContent\n  + chevron + folder/file + Label',kind:'ВЗАИМОДЕЙСТВИЕ'},
  {id:'shell',title:'App shell',detail:'Окно собрано из шапки, дерева, кода и status bar.',height:244,parts:'WindowHeader · ToolbarSurface\nTreeItem[] · Splitter · CodeLine[]\nStatusBar',kind:'КОМПОЗИЦИЯ'},
  {id:'textparts',title:'Текст и состояния',detail:'Подсказки клавиш, пустое состояние и code view.',height:244,parts:'Keycap · BodyText · Paragraph\nEmptyState : Alert\nCodeLine → BodyText + line number',kind:'ВИЗУАЛЬНЫЕ ЧАСТИ'},
  {id:'multiline',title:'Textarea',detail:'Явные переносы строк, отдельная область значения.',height:184,parts:'TextArea → MultilineValue\nTextInput → многострочный TextEdit',kind:'ВЗАИМОДЕЙСТВИЕ'},
  {id:'formatting',title:'Rich text: части',detail:'Панель форматирования отделена от редактора текста.',height:184,parts:'FormattingButton[]\nParagraph · Label\nRichTextEditor требует text engine',kind:'ВИЗУАЛЬНЫЕ ЧАСТИ'},
];
export function extraSpecimens(id,size,state={}) {
  const value=state.range??8, fraction=(value-1)/15;
  switch(id) {
    case 'reveal': return [p('Card','revealCard',18,18,{width:268,height:92,text:'Курсор рядом — дуга на рамке',fontSize:14}),b('SecondaryButton','revealAction',18,134,'Войти в рамку',{width:182}),p('Surface','revealDisabled',212,134,{text:'Off',width:74,height:32,disabled:true})];
    case 'choices': return [b('Checkbox','check',0,4,'Автосохранение',{width:304,checked:state.check??true}),b('Checkbox','mixed',0,44,'Частичный выбор',{width:304,checked:state.mixed===1,indeterminate:(state.mixed??2)===2}),b('Checkbox','disabledCheck',0,84,'Недоступно',{width:304,checked:true,disabled:true}),note('switchText','Анимации интерфейса',0,136,240),b('Switch','switch',260,134,'Анимации интерфейса',{width:44,height:26,checked:state.switch??true})];
    case 'radiochips': return [...choiceGroup({key:'protocol',labels:['HTTP','BitTorrent','FTP'],selected:state.radio??1,y:0}),...['Rust','WASM','Web'].map((text,i)=>b('Chip',`chip${i}`,i*104,128,text,{width:96,height:28,selected:state.chips?.[i]??(i!==1)}))];
    case 'segments': return [p('Surface','segmentTrack',0,0,{width:304,height:38,radius:10,background:{expr:'state.theme.canvas'}}),...buttonGroup({key:'segment',labels:['Web','Native','Mobile'],selected:state.segment??0,x:4,y:4,width:296,height:30}),...buttonGroup({key:'underline',labels:['Обзор','Токены','Экспорт'],selected:state.underline??0,y:70,type:'TabButton',gap:12}),note('selectedPanel',`Раздел: ${['Обзор','Токены','Экспорт'][state.underline??0]}`,0,126)];
    case 'fields': return [note('fieldLabel','Имя проекта',0,0),b('TextField','projectField',0,28,'Имя проекта',{width:304,height:38,value:state.fields?.projectField??'flowget',suffix:'.rs'}),note('fieldHelper','Только латиница и дефис',0,70),b('TextField','errorField',0,104,'Ошибка',{width:304,height:38,value:state.fields?.errorField??'db bill!',error:true}),p('Paragraph','fieldError',0,144,{text:'Недопустимый символ',width:304,height:24,horizontalPadding:0,fontSize:12,color:{expr:'state.theme.dangerInk'}}),b('SearchField','searchField',0,186,'Поиск',{width:304,height:38,value:state.fields?.searchField??'',placeholder:'Поиск по файлам'})];
    case 'range': return [note('rangeCaption',`Параллельные соединения: ${value}`,0,2),b('Slider','rangeSlider',0,38,'Количество соединений',{width:304,height:32,value:{expr:`${fraction*100}%`}}),...numberStepper({key:'range',value,x:90,y:102}),note('rangeHint','1…16 · шаг 1 · стрелки и Home / End',0,150)];
    case 'navigation': return [...breadcrumb({key:'crumb',labels:['forma','src','tokens.rs'],widths:[62,48,84],y:0}),...['Загрузки','Коллекции','Настройки'].map((text,i)=>b('NavigationItem',`side${i}`,0,40+i*44,text,{width:304,height:38,selected:i===(state.side??1)})),b('IconButton','pagePrev',0,194,'Предыдущая страница',{width:32,height:32,icon:'assets/chevron-left.svg'}),...[1,2,3,4,5].map((n,i)=>b('PageButton',`page${i}`,44+i*42,194,String(n),{width:32,height:32,selected:i===(state.page??1)})),b('IconButton','pageNext',268,194,'Следующая страница',{width:32,height:32,icon:'assets/chevron-right.svg'})];
    case 'data': return [...dataTable({key:'repoTable',rows:[['forma','Rust','128 KB'],['studio','JS','458 KB']]}),p('Skeleton','skeletonWide',0,124,{width:210}),p('Skeleton','skeletonNarrow',0,146,{width:136}),...avatarGroup({key:'avatarStack',labels:['АН','МК','ДП','+2'],x:0,y:188}),b('LoadingButton','loading',152,190,'Загрузка',{width:152,disabled:true})];
    case 'overlays': return [b('SelectTrigger','selectToggle',0,4,'Платформа',{width:304,height:38,value:['Web','Native','Mobile'][state.target??0],expanded:state.menu??false}),...(state.menu?[p('Surface','menuSurface',0,48,{width:304,height:112,radius:10,background:{expr:'state.theme.surfaceRaised'}}),...['Web','Native','Mobile'].map((text,i)=>b('MenuItem',`target${i}`,4,52+i*34,text,{width:296,height:34,selected:i===(state.target??0)}))]:[]),b('DisclosureHeader','disclosure',0,174,'Дополнительно',{width:304,value:'Дополнительно',expanded:state.disclosure??false}),...(state.disclosure?[note('disclosedText','Настройка сохраняется локально',12,216,280)]:[])];
    case 'feedback': return state.dialog?dialog({key:'demoDialog',title:'Сохранить изменения?',description:'Данные останутся в этом проекте.'}):[b('PrimaryButton','showDialog',0,2,'Диалог'),b('SecondaryButton','showToast',158,2,'Toast'),b('GhostButton','showTooltip',0,54,'Подсказка'),...(state.tooltip?[p('Tooltip','demoTooltip',0,92,{width:264,text:'Подсказка для действия'})]:[]),...(state.toast?[p('Toast','demoToast',0,152,{width:304,height:76,text:'Сохранено',description:'Сообщение закроется через 2,6 с'})]:[])];
    case 'documents': {const labels=state.documents??['ui.rs','lib.rs','main.rs'];return labels.length?[...documentTabs({key:'doc',labels,selected:state.document??0,width:304,dirty:[labels.indexOf('ui.rs')]}),note('docSelected',`Открыт: ${labels[state.document??0]}`,0,72),note('docHint','Крестик не перекрывает имя файла',0,114)]:[p('EmptyState','closedDocuments',0,18,{width:304,text:'Все вкладки закрыты',description:'Можно восстановить пример'}),b('SecondaryButton','resetDocuments',62,122,'Восстановить',{width:180})];}
    case 'tree': {const rows=state.treeRows??[{index:0,depth:0,branch:true,expanded:true},{index:1,depth:1,branch:false},{index:2,depth:1,branch:true,expanded:true},{index:3,depth:2,branch:false},{index:4,depth:2,branch:false}];const labels=['forma','Cargo.toml','src','lib.rs','tokens.rs'];return [...rows.map((r,i)=>b('TreeItem',`tree${r.index}`,0,4+i*30,labels[r.index],{width:304,height:28,indent:r.depth*14,branch:r.branch,expanded:r.expanded,selected:r.index===(state.treeSelected??3),icon:r.branch?'assets/folder.svg':'assets/file.svg'})),note('treeHint','Стрелки: выбор, раскрытие, родитель',0,198)];}
    case 'shell': {const sidebar=state.sidebar??90; return [p('Card','appWindow',0,0,{width:304,height:232,radius:10}),p('WindowHeader','appHeader',1,1,{width:302,height:30,text:'forma / Studio'}),p('ToolbarSurface','appTools',1,31,{width:302,height:36}),b('GhostButton','appRun',100,33,'Run',{width:56,height:30}),b('GhostButton','appFormat',164,33,'Format',{width:66,height:30}),b('PrimaryButton','appExport',236,36,'Export',{width:62,height:26,fontSize:11}),p('Surface','appSidebar',1,67,{width:sidebar,height:140,radius:0,background:{expr:'state.theme.canvas'},borderWidth:0}),b('TreeItem','appSource',5,74,'src',{width:sidebar-10,height:26,branch:true,expanded:true,indent:0}),b('TreeItem','appFile',5,104,'lib.rs',{width:sidebar-10,height:26,branch:false,selected:true,indent:10}),p('Splitter','appSplitter',sidebar+1,68,{height:138,action:'appSplitter'}),...codeBlock({key:'appCode',x:sidebar+10,y:78,width:294-sidebar,lines:['use forma::Runtime;','','fn main() {','    // интерфейс','}']}),p('StatusBar','appStatus',1,208,{width:302,first:'main',second:'Rust',third:'UTF-8'})];}
    case 'textparts': return [p('Keycap','keyEnter',0,2,{text:'Enter',width:52}),p('Keycap','keyCtrl',64,2,{text:'Ctrl',width:42}),p('Keycap','keyK',118,2,{text:'K',width:24}),p('EmptyState','emptySearch',0,48,{width:304,height:76,text:'Ничего не найдено',description:'Попробуйте другой запрос'}),...codeBlock({key:'codeExample',y:148,lines:['component Demo {','  PrimaryButton {}','}']})];
    case 'multiline': return [b('TextArea','descriptionField',0,4,'Описание',{width:304,height:100,value:state.fields?.descriptionField??'Одни токены — Web, native, mobile.\nЯвные переносы строк сохраняются.\nМожно редактировать текст.'}),note('multilineHint','Enter — новая строка · ⌘/Ctrl+A — всё.',0,132)];
    case 'formatting': return [...['B','I','U','S','H1'].map((text,i)=>b('FormattingButton',`format${i}`,i*42,0,text,{width:34,height:30,selected:state.formatting?.[i]??false})),note('formatBody','Форматирование — отдельная панель.',0,62),note('formatRequirement','Редактирование RTF требует text engine.',0,98),note('formatStatus','Здесь показаны его составные части.',0,134)];
    default: throw Error(`Unknown section: ${id}`);
  }
}
